import { Quiz } from '../types';

export function PrintableQuiz({ quiz }: { quiz: Quiz }) {
  return (
    <div className="hidden print:block p-8 max-w-4xl mx-auto text-black bg-white font-sans">
      <div className="text-center mb-10">
        <h1 className="text-4xl font-bold mb-2">{quiz.title}</h1>
        <p className="text-gray-500">Generated by AI Quiz Generator</p>
      </div>
      
      <div className="space-y-8">
        {quiz.questions.map((q, i) => (
          <div key={i} className="break-inside-avoid">
            <h3 className="text-xl font-semibold mb-4">{i + 1}. {q.question}</h3>
            <div className="space-y-3 pl-6">
              {q.options.map((opt, j) => (
                <div key={j} className="flex items-center gap-4">
                  <div className="w-5 h-5 border-2 border-gray-400 rounded-full"></div>
                  <span className="text-lg">{opt}</span>
                </div>
              ))}
            </div>
          </div>
        ))}
      </div>

      <div className="break-before-page mt-12 pt-8 border-t-2 border-gray-200">
        <h2 className="text-3xl font-bold mb-8">Answer Key</h2>
        <div className="space-y-6">
          {quiz.questions.map((q, i) => (
            <div key={i} className="break-inside-avoid">
              <p className="font-bold text-lg">{i + 1}. {q.correctAnswer}</p>
              <p className="text-gray-700 mt-1">Explanation: {q.explanation}</p>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}
